name: Update Peloton Data

on:
  push:
    branches: main
    
jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup R
      uses: r-lib/actions/setup-r@v2

    - name: Install CRAN dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: |
          any::tidyverse 
          any::httr
          any::jsonlite
          any::glue
          any::devtools
    - name: Install pelotonR from GitHub
      env:
        GITHUB_PAT: ${{ secrets.GIT_PAT }}
      run: Rscript -e 'devtools::install_github("lgellis/pelotonR")'
    - name: Run data collection setup script
      env:
        API_USERNAME: ${{ secrets.API_USERNAME }}
        API_PASSWORD: ${{ secrets.API_PASSWORD }}
      run: Rscript -e 'source("code/data-collection-setup.R")'

    - name: Run data collection update script
      run: Rscript -e 'source("code/data-collection-update.R")'

    - name: Commit and push if changes are made
      run: |
        git config --global user.email "shapiro.tan@gmail.com"
        git config --global user.name "Tanya Shapiro"
        git add data/peloton_data.csv
        git commit -m "Update data" || echo "No changes to commit"
        git push origin
