name: Update Peloton Data

on:
  schedule:
    - cron: '0 0 * * *' # This will run daily at midnight UTC. Adjust the schedule as needed.

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup R
      uses: r-lib/actions/setup-r@v2

    - name: Install CRAN dependencies
      run: |
        install.packages("tidyverse")
        install.packages("httr")
        install.packages("jsonlite")
        install.packages("glue")
        install.packages("devtools")

    - name: Install pelotonR from GitHub
      run: |
        devtools::install_github("lgellis/pelotonR")

    - name: Run data collection setup script
      env:
        API_USERNAME: ${{ secrets.API_USERNAME }}
        API_PASSWORD: ${{ secrets.API_PASSWORD }}
      run: Rscript code/data-collection-setup.R

    - name: Run data collection update script
      run: Rscript code/data-collection-update.R

    - name: Commit and push if changes are made
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add data/peloton_data.csv
        git commit -m "Update data" || echo "No changes to commit"
        git push
